In [1]:
%pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /Users/yaninafontana/anaconda3/envs/clase/lib/python3.10/site-packages (2.0.23)
Requirement already satisfied: pymysql in /Users/yaninafontana/anaconda3/envs/clase/lib/python3.10/site-packages (1.1.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/yaninafontana/anaconda3/envs/clase/lib/python3.10/site-packages (from sqlalchemy) (4.8.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# librerias a importar

import pandas as pd
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

In [2]:
video_games_sales_ori = pd.read_csv('../data/video_games_sales.csv', encoding='latin1') #leo el archivo "INE"

video_games_sales = video_games_sales_ori.copy() #hago una copia

video_games_sales.head() #miro qu√© pinta tiene para empezar a limpiar

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
video_games_sales.columns

Index(['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Critic_Score',
       'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating'],
      dtype='object')

In [4]:
columnas_a_eliminar = ['Global_Sales', 'Critic_Score',
       'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating']

video_games_sales = video_games_sales.drop(columnas_a_eliminar, axis=1)

In [5]:
video_games_sales

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00
...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00

In [6]:
video_games_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
dtypes: float64(5), object(4)
memory usage: 1.1+ MB

In [7]:
unique_count = video_games_sales['Platform'].nunique()
unique_count

31

In [8]:
unique_platform = video_games_sales['Platform'].unique()
unique_platform

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       'PS4', '3DS', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne',
       'WiiU', 'GC', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [9]:
platform_mapping = {
    'Wii': 'Nintendo Wii',
    'NES' : 'NES (Nintendo Entertainment System)', 
    'GB' : 'Nintendo Game Boy', 
    'DS':'Nintendo Dual Screen', 
    'X360': 'Xbox360',
    'PS3': 'PlayStation3', 
    'PS2': 'PlayStation2', 
    'SNES': 'Super Nintendo Entertainment System', 
    'GBA' : 'Game Boy Advance',
    'PS4': 'PlayStation4', 
    '3DS': 'Nintendo 3DS', 
    'N64': 'Nintendo 64', 
    'PS': 'PlayStation', 
    'XB': 'Xbox', 
    '2600': 'Atari 2600', 
    'PSP': 'PlayStation Portable', 
    'XOne': 'Xbox One',
    'WiiU' : 'Nintendo WiiU', 
    'GC' : 'Nintendo GameCube', 
    'GEN': 'Sega Genesis', 
    'DC': 'Sega Dreamcast', 
    'PSV': 'PlayStation Vita', 
    'SAT': 'Sega Saturn', 
    'SCD': 'Sega CD', 
    'WS': 'WonderSwan', 
    'NG': 'Neo Geo', 
    'TG16': 'TurboGrafx-16', 
    'GG': 'Game Gear', 
    'PCFX': 'NEC PC-FX'
}

video_games_sales['Platform'] = video_games_sales['Platform'].replace(platform_mapping)

In [10]:
unique_platform = video_games_sales['Platform'].unique()
print(unique_platform)

['Nintendo Wii' 'NES (Nintendo Entertainment System)' 'Nintendo Game Boy'
 'Nintendo Dual Screen' 'Xbox360' 'PlayStation3' 'PlayStation2'
 'Super Nintendo Entertainment System' 'Game Boy Advance' 'PlayStation4'
 'Nintendo 3DS' 'Nintendo 64' 'PlayStation' 'Xbox' 'PC' 'Atari 2600'
 'PlayStation Portable' 'Xbox One' 'Nintendo WiiU' 'Nintendo GameCube'
 'Sega Genesis' 'Sega Dreamcast' 'PlayStation Vita' 'Sega Saturn'
 'Sega CD' 'WonderSwan' 'Neo Geo' 'TurboGrafx-16' '3DO' 'Game Gear'
 'NEC PC-FX']

In [11]:
unique_count_g = video_games_sales['Genre'].nunique()
unique_count_g

12

In [12]:
unique_genre = video_games_sales['Genre'].unique()
unique_genre

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy', nan], dtype=object)

In [13]:
column_mapping = {
    'Name': 'Nombre',
    'Platform':'Plataforma',
    'Year_of_Release': 'A√±o',
    'Genre': 'G√©nero',
    'Publisher': 'Compa√±√≠a',
    'NA_Sales': 'USA',
    'EU_Sales': 'Europa',
    'JP_Sales': 'Jap√≥n',
    'Other_Sales': 'Otros'
}

video_games_sales = video_games_sales.rename(columns=column_mapping)

In [14]:
unique_count_name = video_games_sales['Nombre'].nunique()
unique_count_name

11562

In [15]:
video_games_sales_cleaned = video_games_sales.dropna()

In [16]:
video_games_sales_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16416 entries, 0 to 16718
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      16416 non-null  object
 1   Plataforma  16416 non-null  object
 2   A√±o         16416 non-null  float64
 3   G√©nero      16416 non-null  object
 4   Compa√±√≠a    16416 non-null  object
 5   USA         16416 non-null  float64
 6   Europa      16416 non-null  float64
 7   Jap√≥n       16416 non-null  float64
 8   Otros       16416 non-null  float64
dtypes: float64(5), object(4)
memory usage: 1.3+ MB

In [17]:
video_games_sales_cleaned

,Nombre,Plataforma,A√±o,G√©nero,Compa√±√≠a,USA,Europa,Jap√≥n,Otros
0,Wii Sports,Nintendo Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45
1,Super Mario Bros.,NES (Nintendo Entertainment System),1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77
2,Mario Kart Wii,Nintendo Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29
3,Wii Sports Resort,Nintendo Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95
4,Pokemon Red/Pokemon Blue,Nintendo Game Boy,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00
...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00
16715,LMA Manager 2007,Xbox360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00
16716,Haitaka no Psychedelica,PlayStation Vita,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00
16717,Spirits & Spells,Game Boy Advance,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00
16718,Winning Post 8 2016,PlayStation Vita,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00

In [18]:

video_games_sales_cleaned['A√±o'] = video_games_sales_cleaned['A√±o'].astype(int)
video_games_sales_cleaned

,Nombre,Plataforma,A√±o,G√©nero,Compa√±√≠a,USA,Europa,Jap√≥n,Otros
0,Wii Sports,Nintendo Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45
1,Super Mario Bros.,NES (Nintendo Entertainment System),1985,Platform,Nintendo,29.08,3.58,6.81,0.77
2,Mario Kart Wii,Nintendo Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29
3,Wii Sports Resort,Nintendo Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95
4,Pokemon Red/Pokemon Blue,Nintendo Game Boy,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00
...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation3,2016,Action,Tecmo Koei,0.00,0.00,0.01,0.00
16715,LMA Manager 2007,Xbox360,2006,Sports,Codemasters,0.00,0.01,0.00,0.00
16716,Haitaka no Psychedelica,PlayStation Vita,2016,Adventure,Idea Factory,0.00,0.00,0.01,0.00
16717,Spirits & Spells,Game Boy Advance,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00
16718,Winning Post 8 2016,PlayStation Vita,2016,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00

In [19]:
video_games_sales_cleaned.to_csv('video_games_ok.csv', index=False)

In [24]:
video_games_sales_cleaned.iloc[6640]

Nombre        Sid Meier's Civilization VI
Plataforma                             PC
A√±o                                  2016
G√©nero                           Strategy
Compa√±√≠a             Take-Two Interactive
USA                                  0.09
Europa                               0.13
Jap√≥n                                 0.0
Otros                                0.02
Name: 6754, dtype: object

In [20]:
from sqlalchemy import create_engine

In [21]:
with open ('pw.txt') as file:
    password = file.read()

In [22]:
str_conn = f'mysql+pymysql://root:{password}@localhost:3306/video_games'
cursor = create_engine(str_conn)

In [ ]:
video_games_sales_cleaned.to_sql(name='video_games_sales',       # nombre de la tabla
            con=cursor,           # conexion al servidor
            if_exists='replace',  # replace sobreescribe la tabla
            index=True)